name: Release Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to release"
        required: true

jobs:
  run_tests:
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

  release:
    runs-on: ubuntu-22.04
    needs: run_tests
    permissions:
      contents: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools build wheel s3pypi

      - name: Build the package
        run: |
          python -m build --outdir dist/

      - name: Attach files to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
          token: ${{ github.token }}
          files: dist/*

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PYPI_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PYPI_S3_SECRET_ACCESS_KEY }}
        run: |
          s3pypi upload dist/* --bucket {{ PYPI_S3_BUCKET }} --region {{ PYPI_S3_REGION }}
